/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        login: [];
        'login.store': [];
        logout: [];
        'password.request': [];
        'password.reset': [
            {
                name: 'token';
                required: true;
            },
        ];
        'password.email': [];
        'password.update': [];
        register: [];
        'register.store': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        'password.confirm': [];
        'password.confirmation': [];
        'password.confirm.store': [];
        'two-factor.login': [];
        'two-factor.login.store': [];
        'two-factor.enable': [];
        'two-factor.confirm': [];
        'two-factor.disable': [];
        'two-factor.qr-code': [];
        'two-factor.secret-key': [];
        'two-factor.recovery-codes': [];
        'two-factor.regenerate-recovery-codes': [];
        'passkey.login-options': [];
        'passkey.login': [];
        'passkey.confirm-options': [];
        'passkey.confirm': [];
        'passkey.registration-options': [];
        'passkey.store': [];
        'passkey.destroy': [
            {
                name: 'passkey';
                required: true;
                binding: 'id';
            },
        ];
        home: [];
        dashboard: [];
        'profile.edit': [];
        'profile.update': [];
        'profile.destroy': [];
        'security.edit': [];
        'user-password.update': [];
        'sessions.index': [];
        'sessions.destroy': [
            {
                name: 'session';
                required: true;
            },
        ];
        'sessions.destroy-other': [];
        'appearance.edit': [];
        'well-known.passkeys': [];
        'security.users.resend-invitation': [
            {
                name: 'user';
                required: true;
                binding: 'id';
            },
        ];
        'security.users.index': [];
        'security.users.create': [];
        'security.users.store': [];
        'security.users.show': [
            {
                name: 'user';
                required: true;
                binding: 'id';
            },
        ];
        'security.users.edit': [
            {
                name: 'user';
                required: true;
                binding: 'id';
            },
        ];
        'security.users.update': [
            {
                name: 'user';
                required: true;
                binding: 'id';
            },
        ];
        'security.users.destroy': [
            {
                name: 'user';
                required: true;
                binding: 'id';
            },
        ];
        'security.roles.index': [];
        'security.roles.create': [];
        'security.roles.store': [];
        'security.roles.show': [
            {
                name: 'role';
                required: true;
                binding: 'id';
            },
        ];
        'security.roles.edit': [
            {
                name: 'role';
                required: true;
                binding: 'id';
            },
        ];
        'security.roles.update': [
            {
                name: 'role';
                required: true;
                binding: 'id';
            },
        ];
        'security.roles.destroy': [
            {
                name: 'role';
                required: true;
                binding: 'id';
            },
        ];
        'security.permissions.index': [];
        'security.permissions.create': [];
        'security.permissions.store': [];
        'security.permissions.edit': [
            {
                name: 'permission';
                required: true;
                binding: 'id';
            },
        ];
        'security.permissions.update': [
            {
                name: 'permission';
                required: true;
                binding: 'id';
            },
        ];
        'security.permissions.destroy': [
            {
                name: 'permission';
                required: true;
                binding: 'id';
            },
        ];
        'security.modules.index': [];
        'security.modules.create': [];
        'security.modules.store': [];
        'security.modules.edit': [
            {
                name: 'module';
                required: true;
                binding: 'id';
            },
        ];
        'security.modules.update': [
            {
                name: 'module';
                required: true;
                binding: 'id';
            },
        ];
        'security.modules.destroy': [
            {
                name: 'module';
                required: true;
                binding: 'id';
            },
        ];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
        'storage.local.upload': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
